# Generated by Django 4.0.4 on 2022-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('equip', models.CharField(max_length=15)),
                ('muscles', models.CharField(max_length=15)),
                ('risk', models.CharField(max_length=15)),
                ('motion', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('time', models.IntegerField()),
                ('space', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
