# Generated by Django 4.0.4 on 2022-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.CharField(max_length=50)),
                ('muscles', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=50)),
                ('motion', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='exer',
        ),
    ]
