# Generated by Django 4.0.4 on 2022-05-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(choices=[('rope', 'rope'), ('band', 'band'), ('box', 'box'), ('kettlebell', 'kettlebell'), ('dumbbell', 'dumbbell'), ('ball', 'ball'), ('bar', 'bar')], max_length=12)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(choices=[('neck', 'neck'), ('shoulder', 'shoulder'), ('bicep', 'bicep'), ('forarm', 'forarm'), ('chest', 'chest'), ('core', 'core'), ('score', 'score'), ('tricep', 'tricep'), ('trap', 'trap'), ('lat', 'lat'), ('lowback', 'lowback'), ('hamstring', 'hamstring'), ('glute', 'glute'), ('calf', 'calf'), ('shin', 'shin'), ('quad', 'quad')], max_length=15)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(choices=[('wrist', 'wrist'), ('elbow', 'elbow'), ('shoulder', 'shoulder'), ('neck', 'neck'), ('lowback', 'lowback'), ('knee', 'knee'), ('ankle', 'ankle')], max_length=12)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='muscle',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Equip',
        ),
        migrations.DeleteModel(
            name='Muscle',
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
